[package]
name = "crash-course-functions-and-modules"
version = "0.1.0"
edition = "2021"
authors = ["Brenon Ortega <brenon.ortega@hotmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
