[package]
name = "terminal_gpt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-openai = "0.17.1"
crossterm = "0.27.0"
tokio = "1.34.0"
